services:
  dev:
    container_name: vite-dev
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - vite-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=development

  prod:
    container_name: webpack-prod
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - vite-network
    environment:
      - NODE_ENV=production

networks:
  vite-network:
    driver: bridge